apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2em-insightops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e2em-insightops
  template:
    metadata:
      labels:
        app: e2em-insightops
        e2em.enabled: "true"
    spec:
      serviceAccountName: insightops-sa
      containers:
        - name: insightops
          image: dev-registry-quay-catalogathon-registry.apps.hthon-dev.svl.ibm.com/sccat-0364257f-ad4c-40c1-a6de-f10ee3ccc875/e2em-insightops:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: E2EM_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: insightops-config
                  key: backend_url
