apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-e2em
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-e2em
  template:
    metadata:
      labels:
        app: mock-e2em
    spec:
      containers:
        - name: mock-e2em
          image: dev-registry-quay-catalogathon-registry.apps.hthon-dev.svl.ibm.com/sccat-0364257f-ad4c-40c1-a6de-f10ee3ccc875/mock-e2em:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mock-e2em
spec:
  selector:
    app: mock-e2em
  ports:
    - port: 8080
      targetPort: 8080
